// Writes src/schemas.ts from schema/*.schema.yaml, so the validator needs no YAML parser at run time.
//   node scripts/build-schemas.mjs
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import yaml from 'js-yaml'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const NAMES = {
  'blocks-index.schema.yaml': 'blocksIndexSchema',
  'fabric.schema.yaml': 'fabricSchema',
  'loom.schema.yaml': 'loomSchema',
  'strand.schema.yaml': 'strandSchema',
  'thread.schema.yaml': 'threadSchema',
  'weave.schema.yaml': 'weaveSchema',
}

export function renderSchemasModule() {
  const files = readdirSync(join(root, 'schema')).filter((file) => file.endsWith('.schema.yaml')).sort()
  let out = '// Generated by scripts/build-schemas.mjs from schema/*.schema.yaml. Do not edit by hand.\n'
  for (const file of files) {
    const name = NAMES[file]
    if (!name) throw new Error(`no export name for schema/${file}`)
    const schema = yaml.load(readFileSync(join(root, 'schema', file), 'utf8'))
    out += `\nexport const ${name}: Record<string, unknown> = ${JSON.stringify(schema, null, 2)}\n`
  }
  return out
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(join(root, 'src', 'schemas.ts'), renderSchemasModule())
}
